import { Text, Box, Spacer, Grid } from '@flexisaf/flexibull2';
import { SectionTitle } from '../../styles/landing/featuresSection.styles';
import Footer from '../../components/landing/footer.components';
import FirstWinnerImg from '../../assets/images/first_winner.jpeg';
import QuizathonBanner from './components/QuizathonBanner';
import SecondWinnerImg from '../../assets/images/second_winner.jpg';
import ThirdWinnerImg from '../../assets/images/third_winner.jpeg';
import {
  Container,
  WinnerContainer,
  PublicContainer,
  BoxWinnerMobile,
} from './styles';
import NavBar from 'components/landing/navBar.component';
import { useNavigate } from 'react-router-dom';
import QouteUp from '../../assets/images/quote-up.svg';
import { useState } from 'react';
// import HeroRegisterImage from '../../assets/images/Registerimage.svg';
// import CountDown from './components/countDown';
// import useQuizathon from 'hooks/general/useQuizathon';
import Slider from 'react-slick';
import ViewPrices from './components/ViewPrices';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
// import SectionLoader from 'components/custom/sectionLoader';
import YoutubeEmbed from './components/YoutubeEmbedVideo';
import QuizathonFaq from './components/QuizathonFaq';

// TODO Remove component as it's no longer in use
const Quizathon = () => {
  const quizathonPageLink = [
    { link: '/', name: 'Home' },
    { link: '/leaderboard', name: 'Leaderboard' },
  ];
  // const { activeQuizathon, getActiveQuizathon, isLoadingActiveQuizathon } =
  //   useQuizathon();
  const [viewPrices, setViewPrices] = useState<boolean>(false);
  const onClose = () => {
    setViewPrices(false);
  };
  const settings = {
    speed: 1000,
    slidesToShow: 3.05,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 8000,
    cssEase: 'linear',
    infinite: true,
    arrows: false,
    responsive: [
      {
        breakpoint: 1000,
        settings: {
          slidesToShow: 2.1,
          slidesToScroll: 1,
        },
      },
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3.1,
          slidesToScroll: 1,
        },
      },
      {
        breakpoint: 600,
        settings: {
          slidesToShow: 1.04,
          slidesToScroll: 1,
        },
      },
    ],
  };

  const navigate = useNavigate();
  // useEffect(() => {
  //   getActiveQuizathon();
  // }, []);
  // if (isLoadingActiveQuizathon) return <SectionLoader />;
  return (
    <>
      <Container>
        <NavBar navLinks={quizathonPageLink} />
        <Spacer space="30" />
        <QuizathonBanner />
        <Spacer space="30" />
      </Container>
      {/* <Box pad="1rem">
        <CountDown
          title={activeQuizathon?.title || 'Countdown'}
          eventStartTime={new Date(activeQuizathon?.startAt as string)}
          eventEndTime={new Date(activeQuizathon?.stopAt as string)}
          showButton={false}
          showDescription={false}
        />
      </Box> */}
      {/* <Spacer space="30" />
      <HeroSection>
        <Box pad="1rem">
          <h2 className="title-text">Register For</h2>
          <h1 className="title-head">Quizathon 2.0!</h1>
          <Spacer space="5" />
          <p className="paragraph">
            <Text bold> Distinction Quizathon 2.0 </Text> is an online academic
            competition designed to challenge student's knowledge and skills in
            a dynamic and interactive manner. Building on the success of the
            inaugural Quizathon, this event aims to engage 1 million students
            from various institutions across Nigeria. The competition will
            consist of curriculum-based questions generated by our AI-powered
            platform, ensuring relevance and alignment with academic standards.
          </p>
          <Spacer space="8" />
          <Desc>
            <Text bold size="1rem">
              Date:
            </Text>
            <Text size="1rem">7th December, 2024</Text>
          </Desc>
          <Spacer space="8" />
          <Desc>
            <Text bold size="1rem">
              Time:
            </Text>
            <Text size="1rem"> 10am - 3pm</Text>
          </Desc>
          <Spacer space="5" />
          <Text size="1rem">
            Click on the <Text bold>“register now”</Text> button to be a part of
            the quizathon 2.0
          </Text>
          <Spacer space="25" />
          <Box display="flex" style={{ gap: '1rem' }}>
            <Button onClick={() => navigate('/register')}>Register Now</Button>
            <Button pale onClick={() => setViewPrices(true)}>
              View Prizes to be won{' '}
            </Button>
          </Box>
          <Spacer space="20" />
        </Box>
        <HeroImageStyle src={HeroRegisterImage} />
      </HeroSection> */}
      <Spacer space="20" />
      <WinnerContainer>
        <BoxWinnerMobile>
          <Text
            className="winner-title"
            block
            bold
            style={{ lineHeight: '1.3', textAlign: 'center' }}
          >
            Winners Of Quizathon 2.0
          </Text>
          <Box
            onClick={() => navigate('/quizathon-winners')}
            className="past-winners"
          >
            See Past Winners
          </Box>
        </BoxWinnerMobile>

        <Spacer space="10" />
        <Text
          size="1rem"
          block
          className="current-title"
          style={{ lineHeight: '1.3', textAlign: 'center' }}
        >
          Here are the current winners for the Quizathon 2.0
        </Text>

        <Spacer space="20" />
        <Box className="winner-container">
          <Grid
            default="repeat(3, 1fr)"
            md="repeat(2, 1fr)"
            sm="repeat(1, 1fr)"
            gap="20px"
          >
            {quizathonWinner.map((winner) => (
              <Box className="winner-bottom-bg" background={winner.color}>
                <Box
                  background="#F2F2F7"
                  className="winner-card"
                  key={winner.id}
                >
                  <Box className="winner-wrapper" background={winner.color}>
                    <Box className="position">
                      <Text size="1rem" block bold>
                        {winner.id}
                      </Text>
                    </Box>
                    <img
                      src={winner.img}
                      alt="winner-image"
                      className="winner-img"
                    />
                  </Box>
                  <Text
                    size="1.1rem"
                    block
                    bold
                    style={{ textAlign: 'center' }}
                  >
                    {winner.name}
                  </Text>
                  <Box>
                    <Text size="1rem" block style={{ textAlign: 'center' }}>
                      {winner.institution}
                    </Text>
                    <Spacer space="5" />
                    <Text
                      size="1rem"
                      block
                      style={{ color: '#7F7F7F80', textAlign: 'center' }}
                    >
                      {winner.points}
                    </Text>
                  </Box>
                </Box>
              </Box>
            ))}
          </Grid>
        </Box>
        <Spacer space="40" />
      </WinnerContainer>
      <PublicContainer>
        <Spacer space="70" />
        <Text
          className="public-title"
          block
          bold
          style={{ lineHeight: '1.3', textAlign: 'center' }}
        >
          Testimonials
        </Text>
        <Spacer space="15" />
        <Text
          className="public-subtitle"
          block
          style={{ lineHeight: '1.3', textAlign: 'center' }}
        >
          Find out what our users are saying about the quizathon
        </Text>
        <Spacer space="20" />

        <Slider {...settings}>
          {publicViews.map((view) => (
            <div key={view.id}>
              <Box
                className="public-card"
                background="#fff"
                style={{ margin: '0 10px' }}
              >
                <img src={QouteUp} alt="quote" className="qoute-img" />
                <Text className="public-subtitle" block>
                  {view.feedback}
                </Text>

                <Box className="public-info">
                  <Text block bold size="1rem">
                    {view.name}
                  </Text>

                  <Spacer space="5" />
                  <Text block size="1rem">
                    {view.institution}
                  </Text>
                </Box>
              </Box>
            </div>
          ))}
        </Slider>

        <Spacer space="40" />
      </PublicContainer>
      <Spacer space="40" />
      <Box>
        <Spacer space="30" />
        <SectionTitle>Quizathon 1.0 Awards Highlight</SectionTitle>
        <Box pad="40px">
          <YoutubeEmbed embedId="OIc5Axdte_c" />
        </Box>
        <Spacer space="20" />
      </Box>
      <Spacer space="40" />
      <QuizathonFaq />
      <Footer />
      <ViewPrices isOpen={viewPrices} onClose={onClose} />
    </>
  );
};

export default Quizathon;

const publicViews = [
  {
    id: 1,
    name: 'Adeniyi Oluwadamilola Joy',
    institution: 'Institute of Information Technology',
    feedback:
      'The quizathon was a very intense activity for me. It was thrilling and indeed mind tasking. I am very happy to know there is a platform like this where wit and endurance can be tested. Thank you FlexiSAF for this opportunity. I look forward to Quizathon 2.0.',
  },
  {
    id: 2,
    name: 'Daniel Adesanya',
    institution: 'University of Ibadan',
    feedback:
      'The FlexiSAF Campus Quizathon 1.0 was a great experience, very competitive and exciting. I really enjoyed it and the result brought a spotlight to me and my school which is a great opportunity.  Thank you FlexiSAF for this great experience.',
  },
  {
    id: 3,
    name: 'GANIYU ABDULLAHI JAYEOLA',
    institution: 'University of Ibadan',
    feedback:
      'The quizathon was a thrilling experience for me. Competing against students from different institutions of higher learning has given me an estimate of my intellectual capabilities and shortcomings. I wish to thank Flexisaf for organizing this event. I look forward to participating in the next edition. Thank you ',
  },
  {
    id: 4,
    name: 'Michael Johnson',
    institution: 'University of Nigeria',
    feedback:
      'The quizathon was indeed an intellectual battle and an avenue for young legal minds like me to hone my academic and studying skills. Many thanks to the organizers of this competition for creating such a noble avenue.',
  },
  {
    id: 5,
    name: 'adeyemi justus',
    institution: 'Crescent University',
    feedback:
      'The quizathon was a very interesting experience. I learned a lot and had fun competing with others. Thank you FlexiSAF for this opportunity. I look forward to Quizathon 2.0.',
  },
  {
    id: 6,
    name: 'Codrette Chissom Namero',
    institution: 'Veritas University',
    feedback:
      'I had an amazing experience participating in the quizathon. It was challenging and fun. Thank you FlexiSAF for this opportunity. I look forward to Quizathon 2.0.',
  },
  {
    id: 7,
    name: 'Rejoice Ikelatu',
    institution: 'University of Port-harcourt',
    feedback:
      'Participating in the quizathon was a very interesting experience. It was both challenging and rewarding. Thank you FlexiSAF for this opportunity.',
  },
  {
    id: 8,
    name: 'Victor Tochukwu Lawrence',
    institution: 'Abubakar Tafawa Balewa University',
    feedback:
      'The quizathon was an amazing experience. It was challenging and engaging. I look forward to Quizathon 2.0. Thank you FlexiSAF for this opportunity.',
  },
  {
    id: 9,
    name: 'Maduekwe Victor Tochukwu Lawrence',
    institution: 'University of Nigeria',
    feedback:
      'Participating in the quizathon was a great experience. It was both fun and educational. Thank you FlexiSAF for this opportunity. I look forward to Quizathon 2.0.',
  },
  {
    id: 10,
    name: 'Michael Johnson',
    institution: 'University of Nigeria',
    feedback:
      'The quizathon was a thrilling experience. It helped me review my knowledge and prepare for my exams. Thank you FlexiSAF for this opportunity. I look forward to Quizathon 2.0.',
  },
];

const quizathonWinner = [
  {
    id: 1,
    name: 'Daniel Adesanya',
    institution: 'University of Ibadan',
    points: '11,927',
    img: FirstWinnerImg,
    color: '#1D4ED8',
  },
  {
    id: 2,
    name: 'Osazuwa Ero',
    institution: 'Federal University of Technology, Minna',
    points: '10,639',
    img: SecondWinnerImg,
    color: '#FF9500',
  },
  {
    id: 3,
    name: 'Barnabas Oluwasegun',
    institution: 'University of Ibadan',
    points: '8,654',
    img: ThirdWinnerImg,
    color: '#187A97',
  },
];
